### ISSUE TITLE
Can I use this on ChiliPeppr.com?

### ISSUE THREAD

**Issue by johnlauer** [presseverykey/everywhere-eagle-viewer#2]
I've got a CNC milling app that I'd like to use this code on. Can I use it if I give you credit on ChiliPeppr?

**Comment by apla** [comment]
I've fixed retina display and I want to fix viewer my own boards. But I'm afraid to do so without proper license for existing code. Do you have an agreement on license?

**Comment by a2800276** [comment]
Is three clause BSD fine with you? Then I'd go ahead and add a License file.

**Comment by apla** [comment]
Yes, this would be great!

Thank you

**Comment by a2800276** [comment]
ok, thanks for the reminder....
